/**
 * The gate scorecard's job is to be honest about four states that are routinely
 * mistaken for each other, and review round 1 of #278 added a fifth confusion: a
 * fold tested only against hand-written fixtures is honest about a payload no
 * producer emits.
 *
 * The SPINE of this suite is therefore the captured REAL-PRODUCER projections
 * under test/fixtures/gate-scorecard/ (generated by
 * test/fixtures/generate-gate-scorecard-fixtures.mjs, which drives Flow's own
 * `initialState`/`evaluateGate`/`applyEvaluation` and captures what the actual
 * `projectFlowRun` emits). Hand-shaped projections appear only for cases the
 * producer cannot emit (unknown verdict vocabulary, legacy route-back forms,
 * malformed input) and they use the REAL nested shape.
 *
 * Confusions pinned here, drawn from defects that actually happened:
 *
 *  - a gate recorded as proven and costed that had never received an evidence write
 *    (the hand-built version of this card) — and its round-1 sequel: an UNREACHED
 *    gate whose lazily-computed "block" status reads as an invocation;
 *  - a refusal counted as a catch, when the claim was re-submitted unchanged and the
 *    work never moved (kontourai/flow-agents#350: 81 refusals, zero route-backs);
 *  - one route-back event counted twice because Flow reports it under two sources;
 *  - zero shown where "we did not measure" was the truth (kontourai/evals#217, #226);
 *  - a verdict quoted without the caveat that disqualified it (kontourai/evals#220).
 */
const assert = require("node:assert/strict");
const { execFileSync } = require("node:child_process");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const test = require("node:test");
const { createGateScorecardProjection } = require("../src/console-foundation/gate-scorecard-projection");

// Types via `import type` (erased at runtime, so it composes with the require above and
// with the package's node --test runner). Without them the callbacks below are implicitly
// any and `npm run typecheck` fails -- which the test RUNNER does not notice, so a green
// run here is not evidence the file typechecks.
import type {
  FlowProjectionEvidence,
  FlowProjectionGate,
  FlowProjectionLike,
  GateScorecardEntry,
  GateScorecardFinding,
} from "../src/console-foundation/gate-scorecard-projection";

const FIXTURE_DIR = path.join(__dirname, "fixtures", "gate-scorecard");
const GENERATOR = path.join(__dirname, "fixtures", "generate-gate-scorecard-fixtures.mjs");
const FIXTURE_NAMES = ["builder-demo.snapshot-a", "builder-demo.snapshot-b", "other-flow", "indeterminate-demo"];

/** A REAL producer payload, captured — never hand-written (finding HIGH-7). */
function fixture(name: string): FlowProjectionLike {
  return JSON.parse(fs.readFileSync(path.join(FIXTURE_DIR, `${name}.json`), "utf8"));
}

/** Hand-shaped projection in the REAL nested shape, for cases the producer cannot
 *  emit. The consumed fields are REQUIRED on FlowProjectionLike (so the drift
 *  alarm has teeth), hence the full-shape defaults here. */
const proj = (over: Partial<FlowProjectionLike> = {}): FlowProjectionLike => ({
  run: {
    run_id: `run-${Math.random().toString(36).slice(2)}`,
    definition_id: "builder.build",
    updated_at: "2026-08-22T00:00:00.000Z",
  },
  definition: null,
  gates: [],
  evidence: [],
  transitions: [],
  route_backs: [],
  ...over,
});

const gate = (over: Partial<FlowProjectionGate> & Pick<FlowProjectionGate, "id" | "status">): FlowProjectionGate => ({
  is_open: false,
  expectations: [],
  evidence: [],
  evidence_refs: [],
  matched_expectations: [],
  ...over,
});

const evidenceItem = (over: Partial<FlowProjectionEvidence> & Pick<FlowProjectionEvidence, "id">): FlowProjectionEvidence => ({
  status: null,
  expectation_ids: [],
  ...over,
});

function fold(projections: FlowProjectionLike[], window?: { since?: string }) {
  const projection = createGateScorecardProjection();
  for (const p of projections) projection.apply(p);
  return projection.materialize(window);
}

function entryFor(card: { entries: GateScorecardEntry[] }, flowId: string, gateId: string): GateScorecardEntry {
  const entry = card.entries.find((e: GateScorecardEntry) => e.flow_id === flowId && e.gate_id === gateId);
  assert.ok(entry, `expected an entry for ${flowId}/${gateId}`);
  return entry!;
}

// ── the real-producer spine ────────────────────────────────────────────────────

test("REAL PRODUCER: run identity is read from the nested payload.run, not a flat field", () => {
  // Round-1 BLOCKING-1: the old fold read flat run_id/flow_id, so every real flow
  // folded to "unknown". The captured payload nests both under `run`.
  const card = fold([fixture("builder-demo.snapshot-a")]);
  assert.deepEqual(card.flows_observed, ["builder.demo"]);
  assert.equal(card.runs_folded, 1);
  assert.equal(card.entries.every((e: GateScorecardEntry) => e.flow_id === "builder.demo"), true);
});

test("REAL PRODUCER: a declared-but-idle wait gate is not an invocation; an unprovable block is INDETERMINATE", () => {
  // The producer projects EVERY declared gate. In snapshot A the run is still on
  // step `plan`: `publish.window` projects "wait" (idle), and `verify.tests`
  // projects a lazily COMPUTED "block" (required evidence missing) although the
  // run never reached it (not open, no evidence). Counting either as invoked was
  // the round-1 defect — and round 2 proved the mirror image: a REAL persisted
  // block can project identically, so the unprovable block is neither a refusal
  // NOR never_invoked. It is indeterminate, explicitly.
  const snapshot = fixture("builder-demo.snapshot-a");
  const verifyGate = snapshot.gates.find((g) => g.id === "verify.tests")!;
  assert.equal(verifyGate.status, "block");        // fixture precondition: the trap is real
  assert.equal(verifyGate.is_open, false);
  const card = fold([snapshot]);

  const idle = entryFor(card, "builder.demo", "publish.window");
  assert.equal(idle.state, "never_invoked");       // "wait" is no verdict at all
  assert.equal(idle.invocations, 0);
  assert.equal(idle.refusals, 0);
  assert.equal(idle.indeterminate, 0);

  const unprovable = entryFor(card, "builder.demo", "verify.tests");
  assert.equal(unprovable.state, "indeterminate");
  assert.equal(unprovable.indeterminate, 1);
  assert.equal(unprovable.invocations, 0);
  assert.equal(unprovable.refusals, 0);

  // ... while the gate the run actually stood at IS invoked, exactly once.
  const reached = entryFor(card, "builder.demo", "plan.review");
  assert.equal(reached.state, "invoked");
  assert.equal(reached.invocations, 1);
});

test("REAL PRODUCER: a persisted block the run advanced past and a lazy computed block are byte-identical — BOTH are indeterminate", () => {
  // Round-2 HIGH-1, the reviewer's scenario reproduced via the generator:
  // `checks.static` carries a REAL evaluated `gate_outcome` "block" (the run
  // then advanced past its step via a sibling gate), `future.check` is only the
  // producer's lazy computation for an unreached step. The projection exposes
  // no field that separates them, so the fold must refuse to guess in EITHER
  // direction for both.
  const snapshot = fixture("indeterminate-demo");
  const real = snapshot.gates.find((g) => g.id === "checks.static")!;
  const lazy = snapshot.gates.find((g) => g.id === "future.check")!;
  const consumedFields = (g: FlowProjectionGate) => ({
    status: g.status,
    is_open: g.is_open,
    evidence: g.evidence,
    evidence_refs: g.evidence_refs,
    matched_expectations: g.matched_expectations,
    accepted_exception_id: g.accepted_exception_id ?? null,
  });
  // Fixture precondition: indistinguishable on every field the fold can consume.
  assert.deepEqual(consumedFields(real), consumedFields(lazy));

  const card = fold([snapshot]);
  for (const gateId of ["checks.static", "future.check"]) {
    const entry = entryFor(card, "indeterminate.demo", gateId);
    assert.equal(entry.state, "indeterminate", `${gateId} must be indeterminate`);
    assert.equal(entry.indeterminate, 1);
    assert.equal(entry.invocations, 0, `${gateId}: never folded into invocations`);
    assert.equal(entry.refusals, 0, `${gateId}: never folded into refusals`);
  }
  // The gate whose evaluation IS provable (accepted exception) stays invoked.
  const proven = entryFor(card, "indeterminate.demo", "review.approve");
  assert.equal(proven.state, "invoked");
  assert.equal(proven.refusals, 0);
});

test("REAL PRODUCER: one route-back event reported under two sources counts exactly once", () => {
  // Flow writes a route-back outcome as BOTH a gate_outcome entry and a paired
  // transition entry in the canonical route_backs[] array (HIGH-5).
  const snapshot = fixture("builder-demo.snapshot-a");
  assert.equal(snapshot.route_backs!.length, 2);   // fixture precondition: both sources present
  assert.deepEqual(new Set(snapshot.route_backs!.map((r) => r.source)), new Set(["gate_outcome", "transition"]));

  const card = fold([snapshot]);
  const entry = entryFor(card, "builder.demo", "plan.review");
  assert.equal(entry.route_backs, 1);
  // The routed-back gate refused once in this snapshot — exactly once, not once
  // per source and not once per refused evidence item (HIGH-6).
  assert.equal(entry.refusals, 1);
});

test("REAL PRODUCER: a later snapshot of the same run SUPERSEDES the earlier one", () => {
  // Snapshot B is the same run after recovery: plan.review passed (its historical
  // route-back survives only as a transition), verify.tests was reached and
  // blocked, publish.window is still idle. Folding A then B must count ONE run
  // and reflect B (MED-8) — not the sum of both snapshots.
  const card = fold([fixture("builder-demo.snapshot-a"), fixture("builder-demo.snapshot-b")]);
  assert.equal(card.runs_folded, 1);

  const plan = entryFor(card, "builder.demo", "plan.review");
  assert.equal(plan.state, "invoked");
  assert.equal(plan.invocations, 1);
  assert.equal(plan.refusals, 0);       // the snapshot's verdict is pass
  assert.equal(plan.route_backs, 1);    // the historical route-back is durable

  const verify = entryFor(card, "builder.demo", "verify.tests");
  assert.equal(verify.state, "invoked"); // now open with evidence attached
  assert.equal(verify.invocations, 1);
  assert.equal(verify.refusals, 1);      // Flow's real "block" status IS a refusal (HIGH-6)

  const idle = entryFor(card, "builder.demo", "publish.window");
  assert.equal(idle.state, "never_invoked");
  assert.equal(idle.runs_observed, 1);
});

test("REAL PRODUCER: re-ingesting the same snapshot does not double-count", () => {
  const snapshot = fixture("builder-demo.snapshot-a");
  const card = fold([snapshot, fixture("builder-demo.snapshot-a")]);
  assert.equal(card.runs_folded, 1);
  assert.equal(entryFor(card, "builder.demo", "plan.review").invocations, 1);
  assert.equal(entryFor(card, "builder.demo", "plan.review").route_backs, 1);
});

test("REAL PRODUCER: evidence naming an undeclared expectation surfaces as a finding, plural expectation_ids and all", () => {
  // HIGH-4: real evidence carries `expectation_ids: string[]`. ev-verify-1 names
  // BOTH the declared "tests.green" and the undeclared "ghost.expectation"; only
  // the ghost may surface, and it must not shrink any denominator.
  const card = fold([fixture("builder-demo.snapshot-b")]);
  assert.equal(card.unattributable.length, 1);
  const [finding] = card.unattributable;
  assert.equal(finding.kind, "undeclared_expectation");
  assert.equal(finding.flow_id, "builder.demo");
  assert.equal(finding.expectation_id, "ghost.expectation");
  assert.equal(finding.evidence_id, "ev-verify-1");
  assert.equal(finding.run_id, "run-builder-demo-1");
  // The declared ids attributed fine — reported nowhere.
  assert.equal(card.unattributable.some((f: GateScorecardFinding) => f.expectation_id === "tests.green"), false);
  // And the gate the evidence belongs to still counts in full.
  assert.equal(entryFor(card, "builder.demo", "verify.tests").invocations, 1);
});

test("REAL PRODUCER: an expectation id DECLARED by two flows is a collision, reported for both", () => {
  // HIGH-4: builder.demo and other.flow both declare "plan.approved" in their
  // gates[].expectations[]. A join on that id would silently attribute one flow's
  // evidence to the other. Ownership comes from declarations — evidence merely
  // naming an id (the ghost) creates no ownership and no collision.
  const card = fold([fixture("builder-demo.snapshot-b"), fixture("other-flow")]);
  const collisions = card.unattributable.filter((f: GateScorecardFinding) => f.kind === "expectation_collision");
  assert.equal(collisions.length, 2);
  assert.equal(collisions.every((f: GateScorecardFinding) => f.expectation_id === "plan.approved"), true);
  assert.deepEqual(new Set(collisions.map((f: GateScorecardFinding) => f.flow_id)), new Set(["builder.demo", "other.flow"]));
  // ghost.expectation is an orphan, not a collision.
  assert.equal(card.unattributable.filter((f: GateScorecardFinding) => f.kind === "undeclared_expectation").length, 1);
  assert.equal(card.unattributable.length, 3);
});

// ── the four states, each asserted AS that state ──────────────────────────────

test("state invoked: a reached gate with a recognized verdict", () => {
  const card = fold([fixture("builder-demo.snapshot-b")]);
  assert.equal(entryFor(card, "builder.demo", "plan.review").state, "invoked");
});

test("state never_invoked: the flow ran and this gate produced no verdict — NOT a zero", () => {
  // The live defect this card was rebuilt to fix: a gate recorded as proven and
  // costed had never received an evidence write. "0 refusals" and "never ran"
  // render identically if the state is not carried explicitly.
  const card = fold([fixture("builder-demo.snapshot-b")]);
  const idle = entryFor(card, "builder.demo", "publish.window");
  assert.equal(idle.state, "never_invoked");
  assert.equal(idle.runs_observed, 1); // the FLOW ran; the gate did not
});

test("state unexercised: a flow with no run in the window, its universe derived from an out-of-window run", () => {
  // Scope is DERIVED, not declared: the fold learns other.flow's gates from a
  // retained projection whose run falls OUTSIDE the window. Collapsing this into
  // never_invoked buries the one idle gate in the flow that DID run under every
  // gate of every flow that did not.
  const old = fixture("other-flow");
  (old.run as { updated_at?: string | null }).updated_at = "2020-01-01T00:00:00.000Z";
  const card = fold([fixture("builder-demo.snapshot-b"), old], { since: "2025-01-01T00:00:00.000Z" });

  const stale = entryFor(card, "other.flow", "intake.review");
  assert.equal(stale.state, "unexercised");
  assert.equal(stale.runs_observed, 0);
  assert.equal(stale.invocations, 0);
  // ... and it is DISTINGUISHABLE from the in-window flow's idle gate.
  assert.equal(entryFor(card, "builder.demo", "publish.window").state, "never_invoked");
  assert.deepEqual(card.flows_observed, ["builder.demo"]);
  assert.equal(card.runs_folded, 1);
  assert.equal(card.window.since, "2025-01-01T00:00:00.000Z");
  // Declaration-derived findings do not depend on the window: the collision on
  // "plan.approved" still surfaces.
  assert.equal(card.unattributable.filter((f: GateScorecardFinding) => f.kind === "expectation_collision").length, 2);
});

test("an OPEN wait gate — reached, but no verdict yet — is still not an invocation", () => {
  // The discriminating case fault injection 1c exposed: reach-corroboration
  // (is_open) is true, but "wait" is not a verdict. A run standing at a
  // no-expectations gate that is waiting for evidence has not invoked it.
  // Without this fixture, "idle gates count as invoked" survives the suite as
  // long as it also checks reach.
  const card = fold([proj({
    gates: [gate({ id: "waiting-gate", status: "wait", is_open: true })],
  })]);
  const entry = entryFor(card, "builder.build", "waiting-gate");
  assert.equal(entry.state, "never_invoked");
  assert.equal(entry.invocations, 0);
  assert.equal(entry.withheld, 0); // no verdict at all is NOT a withheld verdict
});

test("state withheld: a verdict this fold cannot qualify is 'does not qualify', not a guess", () => {
  // kontourai/evals#220: an uncomparable result must not land beside genuinely
  // missing data. The producer's own vocabulary is pass/block/wait/route-back, so
  // this is hand-shaped by necessity — a third-party flow's verdict.
  const card = fold([proj({
    gates: [gate({ id: "g", status: "not-comparable", is_open: true })],
  })]);
  const entry = entryFor(card, "builder.build", "g");
  assert.equal(entry.state, "withheld");
  assert.equal(entry.withheld, 1);
  assert.equal(entry.invocations, 0);
  assert.equal(entry.refusals, 0); // "we could not tell" is NOT "it refused"
});

test("an UNPROVEN unknown verdict is indeterminate, not withheld and not never_invoked", () => {
  // withheld claims "this WAS evaluated and did not qualify" — a claim the
  // projection cannot support without corroboration. Same discipline as the
  // block case: no proof either way, its own number.
  const card = fold([proj({
    gates: [gate({ id: "g", status: "not-comparable" })], // is_open false, nothing attached
  })]);
  const entry = entryFor(card, "builder.build", "g");
  assert.equal(entry.state, "indeterminate");
  assert.equal(entry.indeterminate, 1);
  assert.equal(entry.withheld, 0);
  assert.equal(entry.invocations, 0);
});

// ── refusals and route-backs are independent, exact counts (HIGH-5/HIGH-6) ────

test("a refused gate with a refused evidence item is ONE refusal, not two", () => {
  const card = fold([proj({
    gates: [gate({
      id: "verify-gate", status: "refused", is_open: true,
      evidence: [evidenceItem({ id: "e1", status: "refused" })],
    })],
  })]);
  const entry = entryFor(card, "builder.build", "verify-gate");
  assert.equal(entry.refusals, 1);
  assert.equal(entry.invocations, 1);
  assert.equal(entry.route_backs, 0);
});

test("Flow's real gate status 'block' is a refusal", () => {
  const card = fold([proj({
    gates: [gate({ id: "g", status: "block", is_open: true })],
  })]);
  assert.equal(entryFor(card, "builder.build", "g").refusals, 1);
});

test("a route-back does not add a refusal", () => {
  // The separating case (kontourai/flow-agents#350: 81 refusals, ZERO route-backs
  // — a panel folding one into the other reports an apparatus catching 81 things
  // while catching nothing). A passed gate with a historical route-back:
  const card = fold([proj({
    gates: [gate({ id: "verify-gate", status: "pass" })],
    route_backs: [{ id: "transition.1", source: "transition", gate_id: "verify-gate" }],
  })]);
  const entry = entryFor(card, "builder.build", "verify-gate");
  assert.equal(entry.route_backs, 1);
  assert.equal(entry.refusals, 0);
  assert.equal(entry.invocations, 1);
});

test("a refusal does not add a route-back", () => {
  const card = fold([proj({
    gates: [gate({ id: "g", status: "refused", is_open: true })],
    route_backs: [],
  })]);
  const entry = entryFor(card, "builder.build", "g");
  assert.equal(entry.refusals, 1);
  assert.equal(entry.route_backs, 0);
});

test("legacy producer forms without the canonical array: route_back / route-back / status route-back, deduped by id", () => {
  // HIGH-5's fallback: when route_backs[] is absent, recognize every form the
  // producer family has used — and the same stable id emitted twice counts once.
  // A legacy payload predates the canonical array entirely, so it is DELETED
  // here (the strict FlowProjectionLike type requires it; the runtime tolerates
  // its absence by design).
  const legacy = proj({
    transitions: [
      { id: "t1", type: "route_back", status: null, gate_id: "a" },
      { id: "t2", type: "route-back", status: null, gate_id: "a" },
      { id: "t2", type: "route-back", status: null, gate_id: "a" },     // duplicate re-emission
      { id: "t3", type: "step", status: "route-back", gate_id: "b" },
      { id: "t4", type: "step", status: "allowed", gate_id: "b" }, // not a route-back
    ],
    gates: [gate({ id: "a", status: "pass" }), gate({ id: "b", status: "pass" })],
  });
  delete (legacy as { route_backs?: unknown }).route_backs;
  const card = fold([legacy]);
  assert.equal(entryFor(card, "builder.build", "a").route_backs, 2);
  assert.equal(entryFor(card, "builder.build", "b").route_backs, 1);
});

test("a route-back whose gate lost its outcome still proves the gate evaluated in that run", () => {
  // e.g. a cascade cleared the gate back to wait: the durable route-back event
  // keeps the invocation honest, without re-counting the historical refusal.
  const card = fold([proj({
    gates: [gate({ id: "g", status: "wait" })],
    route_backs: [{ id: "transition.1", source: "transition", gate_id: "g" }],
  })]);
  const entry = entryFor(card, "builder.build", "g");
  assert.equal(entry.state, "invoked");
  assert.equal(entry.invocations, 1);
  assert.equal(entry.route_backs, 1);
  assert.equal(entry.refusals, 0);
});

// ── retention honesty (MED-8) ─────────────────────────────────────────────────

test("apply() takes a defensive deep copy: mutating the caller's object later changes nothing", () => {
  const projection = createGateScorecardProjection();
  const input = proj({ gates: [gate({ id: "g", status: "pass" })] });
  projection.apply(input);
  const before = projection.materialize();

  // The caller now vandalizes its own reference every way that would change the fold.
  (input.gates as unknown as Array<Record<string, unknown>>).push({ id: "forged", status: "pass" });
  (input.gates as unknown as Array<Record<string, unknown>>)[0].status = "refused";
  (input.run as Record<string, unknown>).definition_id = "forged.flow";

  assert.deepEqual(projection.materialize(), before);
  assert.equal(before.entries.length, 1);
  assert.equal(before.entries[0]?.refusals, 0);
});

test("materialize is a pure replay and can be called repeatedly", () => {
  const projection = createGateScorecardProjection();
  projection.apply(fixture("builder-demo.snapshot-b"));
  assert.deepEqual(projection.materialize(), projection.materialize());
});

// ── the rest of the honesty contract ──────────────────────────────────────────

test("cost is absent and says so, never zero", () => {
  // Flow's projection knows what happened, not what it cost. A zero here would be
  // indistinguishable from a genuinely free gate — the same defect that recorded
  // 0 tokens for forty real minutes of spend.
  const card = fold([fixture("builder-demo.snapshot-b")]);
  for (const entry of card.entries) {
    assert.equal(entry.cost, null);
    assert.equal(entry.cost_availability, "unavailable");
  }
});

test("evidence naming an undeclared gate is reported, not dropped", () => {
  const card = fold([proj({
    gates: [gate({ id: "verify-gate", status: "pass" })],
    evidence: [evidenceItem({ id: "e1", gate_id: "ghost-gate" })],
  })]);
  const findings = card.unattributable.filter((f: GateScorecardFinding) => f.kind === "undeclared_gate");
  assert.equal(findings.length, 1);
  assert.equal(findings[0]?.gate_id, "ghost-gate");
  assert.match(findings[0]!.reason, /does not declare/);
});

test("folds gates from any flow, not an allow-list of one kit's", () => {
  // The rescope of console#277: gates are a Flow concept. A projection that knew
  // Builder's gate ids would be blind to every other flow — and would put kit
  // vocabulary in a kit-neutral surface.
  const card = fold([
    proj({ run: { run_id: "r1", definition_id: "knowledge.ingest", updated_at: "2026-08-22T00:00:00.000Z" }, gates: [gate({ id: "classify-gate", status: "pass" })] }),
    proj({ run: { run_id: "r2", definition_id: "some.third-party", updated_at: "2026-08-22T00:00:00.000Z" }, gates: [gate({ id: "whatever-gate", status: "pass" })] }),
  ]);
  assert.deepEqual(card.flows_observed, ["knowledge.ingest", "some.third-party"]);
  assert.deepEqual(card.entries.map((e: GateScorecardEntry) => e.gate_id), ["classify-gate", "whatever-gate"]);
});

test("an unparseable window is reported as no window, not silently applied", () => {
  const card = fold([fixture("builder-demo.snapshot-b")], { since: "not-a-timestamp" });
  assert.equal(card.window.since, null);
  assert.equal(card.runs_folded, 1);
});

test("a run that does not say when it ran stays in the windowed denominator", () => {
  // Dropping it silently would shrink the denominator — the exact move the
  // unattributable list exists to prevent.
  const undated = proj({ gates: [gate({ id: "g", status: "pass" })] });
  (undated.run as { updated_at?: string | null }).updated_at = null;
  const card = fold([undated], { since: "2026-01-01T00:00:00.000Z" });
  assert.equal(card.runs_folded, 1);
  assert.equal(entryFor(card, "builder.build", "g").state, "invoked");
});

test("malformed input is ignored rather than throwing", () => {
  const projection = createGateScorecardProjection();
  projection.apply(null as unknown as FlowProjectionLike);
  projection.apply({} as FlowProjectionLike);
  projection.apply({ gates: [{ status: "pass" }] } as unknown as FlowProjectionLike); // gate with no id
  assert.equal(projection.materialize().entries.length, 0);
});

// ── producer drift (round-2 MEDIUM: the alarm must not be vacuous) ────────────

/** Producer-written timestamps are the only non-deterministic bytes; everything
 *  else must reproduce exactly. */
function normalizeTimestamps(value: unknown): unknown {
  if (typeof value === "string") {
    return /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value) ? "<timestamp>" : value;
  }
  if (Array.isArray(value)) return value.map(normalizeTimestamps);
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([k, v]) => [k, normalizeTimestamps(v)]));
  }
  return value;
}

test("DRIFT: regenerating the fixtures against the INSTALLED @kontourai/flow reproduces the checked-in files", () => {
  // The compile-time alarm pins the TYPE; this pins the WIRE. A Flow upgrade
  // that changes what projectFlowRun emits — field renames, new derivations,
  // reordered arrays — must red this test instead of silently invalidating the
  // fixture spine the whole suite stands on. Timestamps are normalized; nothing
  // else is.
  const outDir = fs.mkdtempSync(path.join(os.tmpdir(), "gate-scorecard-regen-"));
  try {
    execFileSync(process.execPath, [GENERATOR, outDir], { stdio: "pipe" });
    for (const name of FIXTURE_NAMES) {
      const regenerated = normalizeTimestamps(JSON.parse(fs.readFileSync(path.join(outDir, `${name}.json`), "utf8")));
      const checkedIn = normalizeTimestamps(JSON.parse(fs.readFileSync(path.join(FIXTURE_DIR, `${name}.json`), "utf8")));
      assert.deepEqual(regenerated, checkedIn,
        `${name}.json no longer matches the installed producer — regenerate the fixtures and re-review the fold against the new shape`);
    }
  } finally {
    fs.rmSync(outDir, { recursive: true, force: true });
  }
});
